// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// weighted_gaussian_cpp
Rcpp::List weighted_gaussian_cpp(const arma::mat& x, const arma::vec& y, const arma::vec& w);
RcppExport SEXP _SurveyMI_weighted_gaussian_cpp(SEXP xSEXP, SEXP ySEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(weighted_gaussian_cpp(x, y, w));
    return rcpp_result_gen;
END_RCPP
}
// weighted_binomial_cpp
Rcpp::List weighted_binomial_cpp(const arma::mat& x, const arma::vec& y, const arma::vec& w, const int maxit, const double tol);
RcppExport SEXP _SurveyMI_weighted_binomial_cpp(SEXP xSEXP, SEXP ySEXP, SEXP wSEXP, SEXP maxitSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type w(wSEXP);
    Rcpp::traits::input_parameter< const int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(weighted_binomial_cpp(x, y, w, maxit, tol));
    return rcpp_result_gen;
END_RCPP
}
// weighted_poisson_cpp
Rcpp::List weighted_poisson_cpp(const arma::mat& x, const arma::vec& y, const arma::vec& w, const int maxit, const double tol);
RcppExport SEXP _SurveyMI_weighted_poisson_cpp(SEXP xSEXP, SEXP ySEXP, SEXP wSEXP, SEXP maxitSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type w(wSEXP);
    Rcpp::traits::input_parameter< const int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(weighted_poisson_cpp(x, y, w, maxit, tol));
    return rcpp_result_gen;
END_RCPP
}
// run_fast_mvn_em_step
Rcpp::List run_fast_mvn_em_step(arma::mat data, const arma::vec& mu, const arma::mat& Sigma, const arma::vec& weights);
RcppExport SEXP _SurveyMI_run_fast_mvn_em_step(SEXP dataSEXP, SEXP muSEXP, SEXP SigmaSEXP, SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weights(weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(run_fast_mvn_em_step(data, mu, Sigma, weights));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SurveyMI_weighted_gaussian_cpp", (DL_FUNC) &_SurveyMI_weighted_gaussian_cpp, 3},
    {"_SurveyMI_weighted_binomial_cpp", (DL_FUNC) &_SurveyMI_weighted_binomial_cpp, 5},
    {"_SurveyMI_weighted_poisson_cpp", (DL_FUNC) &_SurveyMI_weighted_poisson_cpp, 5},
    {"_SurveyMI_run_fast_mvn_em_step", (DL_FUNC) &_SurveyMI_run_fast_mvn_em_step, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_SurveyMI(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
