# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

weighted_gaussian_cpp <- function(x, y, w) {
    .Call(`_SurveyMI_weighted_gaussian_cpp`, x, y, w)
}

weighted_binomial_cpp <- function(x, y, w, maxit = 50L, tol = 1e-8) {
    .Call(`_SurveyMI_weighted_binomial_cpp`, x, y, w, maxit, tol)
}

weighted_poisson_cpp <- function(x, y, w, maxit = 50L, tol = 1e-8) {
    .Call(`_SurveyMI_weighted_poisson_cpp`, x, y, w, maxit, tol)
}

run_fast_mvn_em_step <- function(data, mu, Sigma, weights) {
    .Call(`_SurveyMI_run_fast_mvn_em_step`, data, mu, Sigma, weights)
}

